version: '3'

services:

  db:
    image: postgres
    deploy:
      mode: replicated
      placement:
         constraints:
         - node.role == manager

  web:
    image: alexxten/dj_blog2:v1
    command: python manage.py runserver 0.0.0.0:8000
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
  


